Api 3/readme update
OwletCare/api-style-guide pull request #10
Opened 2022-03-14 15:58 UTC by jashment

Update readme to reflect Owlet guidelines and processes.
Also reflect build process and requirements for running
locally. 

API-3

2022-03-21 16:21 UTC, DanielMossaband commented on README.adoc
> +    sudo gem install asciidoctor -v 2.0.15
Do we need to install coderay?
I get this error when typing `make all`
```
asciidoctor --failure-level=WARN -D output index.adoc;
asciidoctor: WARNING: optional gem 'coderay' is not available. Functionality disabled.
```

2022-03-21 16:23 UTC, DanielMossaband requested changes

2022-03-21 16:23 UTC, DanielMossaband commented on README.adoc
> +1. https://www.ruby-lang.org/en/documentation/installation/[Install Ruby]
Should probably use this
```
https://github.com/postmodern/chruby
```

2022-03-21 16:41 UTC, jashment commented on README.adoc
> +    sudo gem install asciidoctor -v 2.0.15
I didn't get that error. Does it go away after you install coderay?

2022-03-21 21:23 UTC, jashment commented on README.adoc
> +    sudo gem install asciidoctor -v 2.0.15
Added to the install section and the known errors in the running locally section

2022-03-22 19:45 UTC, Gidgidonihah approved these changes

2022-03-22 19:45 UTC, Gidgidonihah commented on README.adoc
> +    sudo gem install asciidoctor -v 2.0.15
`2.0.17` is the latest.

2022-03-22 19:47 UTC, Gidgidonihah commented
I approved the change, but I would also recommend changing the `next-rule-id` portion of the makefile to start with 1000, rather than where it starts now.

2022-03-22 19:48 UTC, jashment commented
> I approved the change, but I would also recommend changing the `next-rule-id` portion of the makefile to start with 1000, rather than where it starts now.

Good call. I'll change that.

2022-03-22 19:50 UTC, jashment commented on README.adoc
> +    sudo gem install asciidoctor -v 2.0.15
@daniellehanks wasn't there a reason we needed version 2.0.15? Or do we just want the latest?

2022-03-22 19:51 UTC, daniellehanks commented on README.adoc
> +    sudo gem install asciidoctor -v 2.0.15
I always recommend pinning. And that is the version CI is pinned to. If the lastest version passes and you want to update ci-kit that's great.

2022-03-22 19:59 UTC, Gidgidonihah commented
> > I approved the change, but I would also recommend changing the `next-rule-id` portion of the makefile to start with 1000, rather than where it starts now.
> 
> Good call. I'll change that.

OTOH, might not be worth the investment as soon as we add rule #1000.

2022-03-22 20:14 UTC, Gidgidonihah commented
> > > I approved the change, but I would also recommend changing the `next-rule-id` portion of the makefile to start with 1000, rather than where it starts now.
> > 
> > 
> > Good call. I'll change that.
> 
> OTOH, might not be worth the investment as soon as we add rule #1000.

Nope, turns out it isn't written well enough to handle adding a rule 1000. Needs to be updated.

2022-03-22 21:49 UTC, Gidgidonihah approved these changes

2022-03-23 17:08 UTC, DanielMossaband requested changes

2022-03-23 17:08 UTC, DanielMossaband commented on README.adoc
> +1. https://github.com/postmodern/chruby[Install Ruby]
Lol i don't mean for this to be chaotic but chruby just let's you switch ruby versions and it's supposed to be paired with `ruby-install`

You install chruby and that auto changes ruby versions and you never have to touch it once you install and set it up. ruby-install is what you use to install ruby versions and you use it whenever you want to change default/install other ruby versions

I would just change the link to this

```suggestion
1. https://www.ruby-lang.org/en/documentation/installation/#ruby-install[Install Ruby]
```

2022-03-29 20:09 UTC, DanielMossaband approved these changes

2022-03-29 20:10 UTC, merged