API-6: Write section 1
OwletCare/api-style-guide pull request #15
Opened 2022-03-30 16:52 UTC by canada11

JIRA Ticket: [API-6](https://owletcare.atlassian.net/browse/API-6)

Add Intro section. This section was a combination of Zalando's Intro and API Design sections, plus Google's Resource-Oriented design.

2022-04-04 18:30 UTC, DanielMossaband requested changes

2022-04-04 18:30 UTC, DanielMossaband commented on chapters/introduction.adoc
> +=== Conventions used in these guidelines
Weirdness with ===

2022-04-04 18:30 UTC, DanielMossaband commented on chapters/introduction.adoc
> +resource. The methods can be either the standard methods (./0131.md[Get],
Link to methods

2022-04-05 17:15 UTC, canada11 commented on chapters/introduction.adoc
> +=== Conventions used in these guidelines
Header size. Having two ='s make the header into a larger header than I think it needs. It seems to fit better with three ='s than two. To me 🤷

2022-04-05 17:17 UTC, DanielMossaband commented on chapters/introduction.adoc
> +=== Conventions used in these guidelines
Oh! That makes sense!

2022-04-05 17:17 UTC, canada11 commented on chapters/introduction.adoc
> +* Existing APIs if updated can be versioned for a new update
Yeah, this one was carry over from Zalando. Hmmmm 🤔

2022-04-05 17:19 UTC, canada11 commented on chapters/introduction.adoc
> +* Existing APIs if updated can be versioned for a new update
It seems to get at: "If you're updating an API and the style guide has changed, then you can update the API to follow the updates in the style guide." Which seems obvious to me that you would try to do that. Unless someone is thinking that the api was made for an old version of the api style guide and they want to keep it that way so that they don't have to update the whole api with their small change.

2022-04-05 17:19 UTC, canada11 commented on chapters/introduction.adoc
> +* Existing APIs if updated can be versioned for a new update
Maybe I'll just delete this bullet point.

2022-04-05 17:20 UTC, canada11 commented on chapters/introduction.adoc
> +* Existing APIs if updated can be versioned for a new update
Hmmm, but the three points it's covering is: Existing apis, new apis, and clients.

2022-04-05 17:21 UTC, DanielMossaband commented on chapters/introduction.adoc
> +* Existing APIs if updated can be versioned for a new update
pls edit your comment sir. I keep getting pinged per new comment

2022-04-05 17:22 UTC, canada11 commented on chapters/introduction.adoc
> +* Existing APIs if updated can be versioned for a new update
So for existing API's: They can stick to the old api guidelines the api was built with, but if you want to update the api for the new guidelines, then make a version change to the api for the new style guide changes.

2022-04-05 19:15 UTC, DanielMossaband requested changes
Looks good! I'll wait to approve until build works

2022-04-05 20:16 UTC, DanielMossaband approved these changes

2022-06-13 19:26 UTC, merged