Update section 5
OwletCare/api-style-guide pull request #16
Opened 2022-03-30 18:10 UTC by DanielMossaband

2022-04-05 19:49 UTC, canada11 commented on chapters/security.adoc
> +The bearer security schema can than be applied to all API endpoints.
*then be applied

2022-04-05 19:50 UTC, canada11 requested changes

2022-04-05 19:50 UTC, canada11 commented on chapters/security.adoc
> +The bearer security schema can than be applied to all API endpoints.
*then be applied

2022-04-06 16:20 UTC, jashment approved these changes

2022-04-06 16:22 UTC, canada11 approved these changes
🍰

2022-04-06 16:22 UTC, merged