Api 9/section 4
OwletCare/api-style-guide pull request #18
Opened 2022-03-31 22:23 UTC by jashment

Update section 4 to be in line with Owlet's meta data
guidelines. Delete [215] and update [219]

API-9

2022-04-04 18:16 UTC, DanielMossaband requested changes

2022-04-04 18:16 UTC, DanielMossaband commented on chapters/meta-information.adoc
> +Following OpenAPI extension properties *may* be provided in addition:
Should

2022-04-04 18:16 UTC, DanielMossaband commented on chapters/meta-information.adoc
> +<functional-hostname>  ::= <functional-name>.owletcare.com
owletdata

2022-04-05 19:51 UTC, canada11 approved these changes
Approved with changes already requested from @DanielMossaband

2022-04-11 16:44 UTC, DanielMossaband approved these changes

2022-04-11 16:46 UTC, merged